fix ncurses.h include
Commit 58559a5b64a3634460536d6397ca382a54b599f0 was not backported from
3.3.17 to 4.0.0 resulting in the following build failure when ncursesw
headers are not installed in ../usr/include/ncursesw/..:

src/watch.c:56:11: fatal error: ncursesw/ncurses.h: No such file or directory
   56 | # include <ncursesw/ncurses.h>
      |           ^~~~~~~~~~~~~~~~~~~~

Fixes:
 - http://autobuild.buildroot.org/results/b7573be2e78f3d224f48cb3f52087e3d227d58e3

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>