Makefile.am: Add ncurses cflags to top and slabtop
If the ncurses library is installed in an unusual spot the compilier
won't find them without these flags:

gcc -std=gnu99 -DHAVE_CONFIG_H -I.  -include ./config.h -I. -I./include -Wno-unused-result -DLOCALEDIR=\"$PREFIX/share/locale\"  -Iproc -O2 -pipe -fno-plt -fexceptions -Wp,-D_FORTIFY_SOURCE=2,-D_GLIBCXX_ASSERTIONS -Wformat -Werror=format-security -Wno-psabi -fstack-clash-protection -MT slabtop.o -MD -MP -MF $depbase.Tpo -c -o slabtop.o slabtop.c &&\
mv -f $depbase.Tpo $depbase.Po
slabtop.c:31:10: fatal error: ncurses.h: No such file or directory

Signed-off-by: Craig Small <csmall@dropbear.xyz>

References:
 !134