build-sys: Have errors for missing po4a
Most of the time, po4a is not required and the translated man
pages are not translated, but sometimes (such as make dist) you
always want them available.

make -C po-man man.stamp, or its dependents, previous would give
some obscure error; either about running a flag or missing file,
it now explicitly talks about the issue:

make[4]: Entering directory '/home/csmall/Projects/procps/procps/po-man'
make  \
  top_distdir="../procps-ng-4.0.4.195-e684a-dirty" distdir="../procps-ng-4.0.4.195-e684a-dirty/po-man" \
  dist-hook
make[5]: Entering directory '/home/csmall/Projects/procps/procps/po-man'
error: You need to install the po4a package.
make[5]: Leaving directory '/home/csmall/Projects/procps/procps/po-man'
make[5]: *** [Makefile:535: check-po4a] Error 1

Signed-off-by: Craig Small <csmall@dropbear.xyz>